##Spring Configuration
server:
  port: 8070
spring:
  application:
    name: taller_logs
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
