server:
  port: 8070
spring:
  webflux:
    base-path: /api/v1
  application:
    name: "taller_logs"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "${MONGO-URI}"
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
routes:
  path-mapping:
    logs: "/logs"
    logs-id: "/logs/{application}"
    log: "/log"


