server:
  port: 9080
spring:
  application:
    name: "taller_docker_cliente"
  devtools:
    add-properties: false
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
adapter:
  restconsumer:
    timeout: 5000
    url: "${URL-SERVIDOR}"
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
jwt:
  json-exp-roles: "/roles"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
