global:
  scrape_interval:     2s # Frecuencia de rastreo predeterminada.
  evaluation_interval: 2s # Frecuencia de evaluación predeterminada.

scrape_configs:
  - job_name: 'api-rest'
    static_configs:
      - targets: ['api-rest:8090']  # Dirección del microservicio api-rest
    metrics_path: /api/v1/actuator/prometheus  # Ruta de los endpoints de métricas

  - job_name: 'logs-rest'
    static_configs:
      - targets: ['logs-rest:8070']  # Dirección del microservicio logs-rest
    metrics_path: /api/v1/actuator/prometheus  # Ruta de los endpoints de métricas